#install.packages("tidyquant")
#install.packages("tidyverse")
#install.packages("quantmod")
#install.packages("xts")
#install.packages("zoo")
#install.packages("PerformanceAnalytics")
#install.packages("alphavantager")
#install.packages("TTR")
#install.packages("dygraphs")
#install.packages("purrr")
#install.packages("purrrlyr")
#install.packages("rlang")
#install.packages("pracma")
#install.packages("IBrokers")
#install.packages("timetk")

library(tidyquant)
library(tidyverse)
library(quantmod)
library(xts)
library(zoo)
library(PerformanceAnalytics)
library(alphavantager)
library(TTR)
library(dygraphs)
library(purrr)
library(purrrlyr)
library(rlang)
library(pracma)
library(IBrokers)
library(timetk)
library(dplyr)
library(ggplot2)
library(rpart)

if (Sys.info()['sysname'] == "Darwin"){
  source(paste(getwd(), 'R/write_ticker_csv.R', sep = "/"))
  source(paste(getwd(), 'R/extend_yahoo_quantmod.R', sep = "/"))
  source(paste(getwd(), 'R/extend_av_quantmod.R', sep = "/"))
  source(paste(getwd(), 'R/local_data_access.R', sep = "/"))
  source(paste(getwd(), 'R/secure_api_dataAccess.R', sep = "/"))
  api_key_file<-paste(getwd(), "../../../data/ghazy_mahjub_api_keys.csv", sep = "/")
  yahoo_stock_prices_dir<-paste(getwd(), "../../../data/yahoo/", sep = "/")
  av_stock_prices_dir<-paste(getwd(), "../../../data/alphavantage/", sep = "/")
} else {
  source(paste(getwd(), 'R/write_ticker_csv.R', sep = "/"))
  source(paste(getwd(), 'R/extend_yahoo_quantmod.R', sep = "/"))
  source(paste(getwd(), 'R/extend_av_quantmod.R', sep = "/"))
  source(paste(getwd(), 'R/local_data_access.R', sep = "/"))
  source(paste(getwd(), 'R/secure_api_dataAccess.R', sep = "/"))
  api_key_file<-paste(getwd(), "..\\..\\..\\..\\data\\ghazy_mahjub_api_keys.csv", sep = "\\")
  yahoo_stock_prices_dir<-paste(getwd(), "..\\..\\..\\..\\data\\yahoo\\", sep = "\\")
  av_stock_prices_dir<-paste(getwd(), "..\\..\\..\\..\\data\\alphavantage\\daily\\", sep ="\\")
}
start_date<-"2017-01-01"
