install.packages("tidyquant")
install.packages("tidyverse")
install.packages("quantmod")
install.packages("xts")
install.packages("zoo")
install.packages("PerformanceAnalytics")
install.packages("alphavantager")
install.packages("TTR")
install.packages("dygraphs")
install.packages("purrr")
install.packages("purrrlyr")
install.packages("rlang")
install.packages("pracma")
install.packages("IBrokers")

library(tidyquant)
library(tidyverse)
library(quantmod)
library(xts)
library(zoo)
library(PerformanceAnalytics)
library(alphavantager)
library(TTR)
library(dygraphs)
library(purrr)
library(purrrlyr)
library(rlang)
library(pracma)
library(IBrokers)

if (Sys.info()['sysname'] == "Darwin"){
  source(paste(getwd(), 'R/write_ticker_csv.R', sep = "/"))
  source(paste(getwd(), 'R/extend_yahoo_quantmod.R', sep = "/"))
  yahoo_stock_prices_dir<-paste(getwd(), "../../../data/yahoo/", sep = "/")
} else {
  source(paste(getwd(), 'R/write_ticker_csv.R', sep = "/"))
  source(paste(getwd(), 'R/extend_yahoo_quantmod.R', sep = "/"))
  yahoo_stock_prices_dir<-paste(getwd(), "..\\..\\..\\..\\data\\yahoo\\", sep = "\\")
}
start_date<-"2017-01-01"
